{
 "title": "APM DEMO Service Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "query_result(count by (service_name)(count_over_time(traces_span_metrics_calls_total[$__range])))"
    }
   },
   {
    "name": "operation",
    "query": {
     "query": "query_result(count by (span_name)(count_over_time(traces_span_metrics_calls_total{service_name=\"$service\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(traces_span_metrics_duration_seconds_bucket{service_name=\"$service\", span_name=~\"$operation\"}[$__rate_interval])))",
     "legendFormat": "95%ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(traces_span_metrics_duration_seconds_bucket{service_name=\"$service\", span_name=~\"$operation\"}[$__rate_interval])))",
     "legendFormat": "99%ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(traces_span_metrics_duration_seconds_bucket{service_name=\"$service\", span_name=~\"$operation\"}[$__rate_interval])))",
     "legendFormat": "50%ile"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(traces_span_metrics_calls_total{service_name=\"$service\", span_name=~\"$operation\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(traces_span_metrics_calls_total{service_name=\"$service\", span_name=~\"$operation\", status_code=\"STATUS_CODE_ERROR\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (span_name, le) (rate(traces_span_metrics_duration_seconds_bucket{service_name=\"$service\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (span_name) (rate(traces_span_metrics_calls_total{service_name=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (span_name) (rate(traces_span_metrics_calls_total{service_name=\"$service\", status_code=\"STATUS_CODE_ERROR\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"opentelemetry-demo/adservice\"}"
    }
   ]
  }
 ]
}